version: '2'
volumes:
    node-red-data:
services:
  influxdb:
    build: influxdb
    container_name: influxdb
    privileged: true
    volumes:
        - mnt/usb:/mnt/usb
    ports:
      - "8086:8086" 
      - "8089:8089"
    restart: always
  grafana:
    build: grafana
    ports:
       - "3000:3000"
    depends_on:
       - influxdb
    restart: always
  mqtt:
    image: panuwitp/mosquitto-arm
    ports:
      - "1883:1883"
  node-red:
    build: node-red
    volumes:
       - 'node-red-data:/data'
    ports:
       - "1880:1880"
    depends_on:
        - mqtt
    restart: always
